apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: homework
spec:
  volumes:
    - name: wwwroot
      emptyDir: {}
  initContainers:
    - name: init-index
      image: busybox
      volumeMounts:
        - mountPath: /init
          name: wwwroot
      command:
        [
          "/bin/sh",
          "-c",
          '(echo -e "<html><head><title>Init date...</title></head><body>";date; echo -e "</body></html>") > /init/index.html',
        ]
  containers:
    - name: webserver
      image: nginx
      volumeMounts:
        - mountPath: /homework
          name: wwwroot
      ports:
        - containerPort: 8000
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "/bin/rm -fv /homework/index.html"]
